### ISSUE TITLE
How to call manually?

### ISSUE THREAD

**Issue by rodenberg** [amazingSurge/jquery-slidePanel#1]
I am using your library to display a table of properties (for real estate) and I have a cartodb map embedded at the top of the page. When a person clicks on a property in the map, I would like to trigger the call to open the slidepanel via javascript (because I don't have the ability to tag a property with a data-uri attribute). 

Is there any way to do this?

**Comment by ptyz030529** [comment]
You can try the code like this

` $.slidePanel.show({
          url: url
        }, options);`

**Comment by rodenberg** [comment]
That worked, thank you!
